
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package calc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NON = 4;
  public static final int LP = 5;
  public static final int BOOL = 13;
  public static final int VA = 12;
  public static final int ET = 3;
  public static final int SET = 8;
  public static final int EOF = 0;
  public static final int EQ = 7;
  public static final int NL = 9;
  public static final int error = 1;
  public static final int OU = 2;
  public static final int DP = 11;
  public static final int PI = 10;
  public static final int RP = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OU",
  "ET",
  "NON",
  "LP",
  "RP",
  "EQ",
  "SET",
  "NL",
  "PI",
  "DP",
  "VA",
  "BOOL"
  };
}

