
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package calc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LP = 6;
  public static final int MULT = 4;
  public static final int CTE = 9;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int NL = 8;
  public static final int SUB = 3;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int RP = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "SUB",
  "MULT",
  "DIV",
  "LP",
  "RP",
  "NL",
  "CTE"
  };
}

